### ISSUE TITLE
Seti Classic?

### ISSUE THREAD

**Issue by iadj** [jesseweed/seti-ui#264]
I really prefer the previous UI as compared to the latest updated one. The bolder, bigger letters are distracting to me. I'd suggest releasing a 'Classic' version since the current update is a huge change.

**Comment by petemill** [comment]
At the moment, until either someone publishes 'seti-classic' in apm or the issues we're experiencing are fixed, you can use the pre-v1 version by doing the following:

```
apm uninstall seti-ui
cd [somwhere]...
git clone git@github.com:jesseweed/seti-ui.git
cd seti-ui
git checkout v0.9.2
apm link .
```

Note though that I think you'll need to uninstall then reinstall from atom in order to get further updates and switch to v1.

*Unfortunately the `apm install seti-ui@0.9.2` command ins't working - looks like apm cannot find the older versions*

**Comment by timnew** [comment]
Luckily to know that I'm not the only one who doesn't like the latest update.

Seti series is a great Atom theme, which is also the reason transferred me into a loyal user from a Sublime user. 

But I'm kind of feeling sad to see the latest Seti UI update. It adds support to color schemes, but most of them are so shiny that distracts me. 

So yes, if possible, I would like to downgrade it to the classic version.

IMHO, the latest update significantly changed the UI look.  I'm not sure whether it should be still named under "seti".

Or @jesseweed Is that possible for you provide another package before the update as "seti classic"?

**Comment by bruinebeer** [comment]
I think a lot of us are very unhappy about the UI changes, they were just way to drastic. It's not like all of us were happy seti-beta users. Ok of course i downloaded seti-beta to check it out, but that was it, maybe more people did the same thing giving a false feeling of the beta theme being popular or accepted.

I would rather suggest calling the new version Seti-neo and reverting seti to its old glory. ^^

**Comment by vermotr** [comment]
I agree with you then I forked (v0.9.2.) and I published it: [seti-classic](https://atom.io/themes/seti-classic)

**Comment by bruinebeer** [comment]
@vermotr Icons are not rendering

**Comment by Leeds-eBooks** [comment]
@bruinebeer Add https://atom.io/packages/file-icons for a quick fix!

**Comment by GradyD** [comment]
I also agree with this. I just spent the time today to update all of my packages and first I thought my theme had changed. 

@jesseweed can you provide the option to revert these changes back or something?

I have not confirmed this but my guess is that this theme is built for a high resolution screen/monitor. It takes up much more screen real estate on a not so great monitor.

**Comment by Leeds-eBooks** [comment]
@GradyD You can install @vermotr 's fork https://atom.io/themes/seti-classic – it works great (as long as you install https://atom.io/packages/file-icons too) and is back to the good old Seti! I personally think the new Seti will be nice once all the problems are ironed out, but the classic Seti has become for me visually synonymous with Atom itself so I can't really live without it. @jesseweed should be proud of his achievement with the original Seti and it might make sense for him to link to `seti-classic` in the new Seti's `README`.

**Comment by vermotr** [comment]
@bruinebeer, @Leeds-eBooks I fixed broken icons.

@GradyD 

I will try to maintain the new repo (seti-classic) so if you find an issue do not hesitate to open a ticket.

**Comment by Benjamski** [comment]
Is this thread addressing the much larger sizes of the tabs, treeview and linter errors? I was going to open an issue about that but I just want to make sure that's not part of this issue. 

I love the setiui and most of the changes in the new update are ok with me but the tabs, treeview and linter errors are HUGE. The tabs are so big that they fill my screen and the filenames are unreadable, aalmostrendering the feature useless.  The linter just takes up way too much of the screen and the same with the treeview. Is there any way to just adjust the sizes of those three aspects without reverting to classic?

https://gyazo.com/d55214d7b5eb4b37362353973f710c51 

Am I wrong to be bothered by how much of my screen is lost in this update I can only even see as much of READ... of the README.md file and it's the only one open o_0

**Comment by iadj** [comment]
@Benjamski You can turn off the padding in the theme settings, although it still appears to be bigger and clunkier.

**Comment by Benjamski** [comment]
@iadj that's awesome! It definitley helps alot and I like the setup you're working with too. Why is it always hard to find a syntax theme with totally flat dark background in the body? I'm not a fan off all the off-black or grayish stuff.

**Comment by jesseweed** [comment]
Hey guys, so just to add a little more clarify of this. The point of the update wasn't to completely re-create the theme. In fact the whole idea of the "compact mode" in settings was to allow to keep the old Seti view with smaller tabs, less spacing, etc. After 6 months staring at the new theme though, it's possible that compact mode diverged more than I planned.

There's also a handful of bugs cropped up in compact mode I need to fix. I plan to hit those this week and will try get compact mode in closer parity with the old seti look as well for those who prefer the "classic" look at the same time. I haven't use 0.9 in over 6 months, and obviously compact mode isn't as close to it as I thought, so I'll do a comparison of the 2 as I make the compact mode adjustments.

Anyway, the point of the update was to give everybody more options on how the ui looks, not force everyone into one new look. So I'll keeping working on the compact mode until it gets closer to the feel of 0.9. 

Cheers!

**Comment by Benjamski** [comment]
@jesseweed  Thanks for all your work on this theme and I really want to make clear how much I'm not shaking my fist at you or anything. I actually love the UI changes that I've made conscious notice of and the only part that I wasn't crazy about was losing so much editor space to the linters, tabs and treeview. I've switched to compact and so far no bugs and I'm really happy with it.

Looking forward to any and all work on it and just want you to know how grateful we are for such a beautiful ui

**Comment by iadj** [comment]
@jesseweed You're awesome! Thanks for clarifying. Looking forward to the updates!

**Comment by jesseweed** [comment]
Hey guys, take a look at compact mode in the 1.1 update I just pushed and let me know what you think. Obviously 1.x is never going to be exactly like the previous 0.x version (otherwise what's the point in updating), but I think the update addresses most of the major gripes. I'm pretty happy with where it's at (notwithstanding any bugs of course), so I don't plan to make many more changes to the compact view from here. That said, let me know if there's any major pain points you guys are still seeing, and I'll address what I can & think makes sense.

### Screenshots for visual comparison:

##### Seti 0.9
![screen shot 2016-05-09 at 10 32 55 pm](https://cloud.githubusercontent.com/assets/719964/15137682/29c9313e-1640-11e6-83d8-bc29edb1d6c6.png)

##### Seti 1.1
![screen shot 2016-05-09 at 11 39 06 pm](https://cloud.githubusercontent.com/assets/719964/15137687/2f37c14e-1640-11e6-8309-0ac2b3e75163.png)
_compact mode on, & sf ui font selected_

**Comment by iadj** [comment]
@jesseweed Much more convenient for those who prefer the seti-classic! There's 2 things that bother me after a few minutes of use:

1. The pointer cursor style in the tree view. Files don't have a pointer cursor by default on any OS, so it feels kind of weird (as if they're anchors to URLs instead of files).

2. The Search bar's text field styling feels very out of proportion being full white, with black placeholder text (making it seem like it's already filled in instead of being a placeholder). Here's a comparison:

Classic: ![Classic](https://i.gyazo.com/ec679527625173a2af29e834642302e5.png)

New: ![New](https://i.gyazo.com/55d0028cc85700a1e1ab6f4f7c871354.png)

**Comment by Leeds-eBooks** [comment]
@iadj see also #259

**Comment by NerdPad** [comment]
I liked how the previous version was "compact". The "compact" feature on the new version, isn't really compact. Everything is so big, and bold.

**Comment by loki0609** [comment]
Thanks @jesseweed for your work on this, it's bee a great UI. The new changes to the compact mode has definitely helped and feels much more like the previous version.  I do want to second iadj comment on the find bar. The white just glares way to much for a dark theme like this, I normally just left the bar open but I'm finding myself having to close it now because of the white. Also, I can't click and drag the folder view scroll bar. I can use my mouse wheel in that area but I can't actually grab it.

**Comment by jesseweed** [comment]
Hey guys, I think most of the remaining concerns noted above should be fixed in 1.2.3: Reduced status bar size, tree view size, and darkened the input colors.

There's an outstanding bug for the scrollbar.

Going to close this out, but feel free to create additional issues if you find more specific things you'd like to see addressed.

**Comment by Leeds-eBooks** [comment]
This is fantastic!

**Comment by loki0609** [comment]
PERFECT! Looks great, thanks!

**Comment by Benjamski** [comment]
This looks fantastic! Thank you!

**Comment by busheezy** [comment]
Thanks!  My treeview was unusable.
